// Grounded Q&A over the result bundle (ADR-0002). The AI may state only numbers present in the
// bundle — fabricating a statistic is the one unforgivable failure (evals/groundedness). When a live
// LLM credential is present, the answer is generated by Claude under a grounding system prompt; when
// not, a deterministic offline answerer covers a few intent types from the same digest — so the
// feature is demonstrable keyless and the groundedness gate passes either way.
import type { ResultBundle } from "@verdant/contracts";
import { bundleDigest, segmentsOf } from "./digest";
import { complete } from "./llm";

const GROUNDED_SYSTEM = `You are Verdant's breeding-analysis assistant. You explain a completed
analysis to a plant breeder in plain language.

HARD RULES (non-negotiable):
- Answer ONLY from the RESULT BUNDLE DIGEST below. It is the single source of truth.
- Every NUMBER you state must appear verbatim in the digest. Never compute a new statistic, average,
  sum, or estimate. Never invent a value.
- If the answer is not in the digest, say so plainly and suggest what analysis would produce it.
- Be concise and concrete. Cite the figures you use. Do not speculate beyond the data.`;

export interface Answer {
  text: string;
  mode: "live" | "offline";
  model: string | null;
}

/** Grounded answer for the UI — carries whether it came from the live model or the offline fallback. */
export async function answer(question: string, bundle: ResultBundle): Promise<Answer> {
  const system = `${GROUNDED_SYSTEM}\n\n=== RESULT BUNDLE DIGEST ===\n${bundleDigest(bundle)}`;
  const llm = await complete(system, question);
  if (llm) return { text: llm.text, mode: "live", model: llm.model };
  return { text: answerOffline(question, bundle), mode: "offline", model: null };
}

/** The eval/CI entrypoint — plain string, deterministic, no credential needed. Conforms to the
 *  evals/groundedness VERDANT_ANSWERER contract: answer(question, bundle) -> string. */
export async function answerText(question: string, bundle: ResultBundle): Promise<string> {
  return (await answer(question, bundle)).text;
}

// --- Offline deterministic answerer ------------------------------------------------------------
// Handles a few common intents straight from the bundle (all numbers are bundle figures, so it passes
// the groundedness checker). Not natural language — a stand-in until an API key enables the live path.

function topForSegment(bundle: ResultBundle, seg: string | undefined, n = 5): string {
  const idx = bundle.indices?.find((i) => i.kind === "weighted" && (!seg || i.segment_id === seg))
    ?? bundle.indices?.find((i) => i.kind === "weighted");
  const rows = (idx?.ranking ?? []).slice(0, n).map((r) => `#${r.rank} ${r.germplasm_id} (index ${r.score ?? "—"})`);
  return rows.length ? rows.join(", ") : "no ranking available";
}

/** The deterministic, key-free answerer (also the CI groundedness gate's subject). Every number it
 *  emits comes from the bundle, so its output is grounded by construction. */
export function answerOffline(question: string, bundle: ResultBundle): string {
  const q = question.toLowerCase();
  const segs = segmentsOf(bundle);
  const seg = segs.find((s) => q.includes(s.toLowerCase()));
  const note = "\n\n(Offline mode — no Anthropic API key configured. This deterministic answer is drawn straight from the result bundle; set ANTHROPIC_API_KEY for full natural-language answers.)";

  // heritability / h2
  if (/(heritab|h2|h²)/.test(q)) {
    const t = bundle.traits?.find((tr) => q.includes(tr.variable_id.toLowerCase()));
    if (t) return `Heritability (h²) of ${t.variable_id} is ${t.heritability?.value ?? "—"}.${note}`;
    const all = (bundle.traits ?? []).map((tr) => `${tr.variable_id} h²=${tr.heritability?.value ?? "—"}`).join("; ");
    return `Per-trait heritability: ${all}.${note}`;
  }
  // correlation
  if (/correlat/.test(q)) {
    const gc = bundle.genetic_correlations;
    if (gc?.variable_ids?.length && gc.matrix?.length) {
      const pairs: string[] = [];
      for (let i = 0; i < gc.variable_ids.length; i++)
        for (let j = i + 1; j < gc.variable_ids.length; j++)
          pairs.push(`${gc.variable_ids[i]} × ${gc.variable_ids[j]} = ${gc.matrix[i]?.[j] ?? "—"}`);
      return `Genetic correlations: ${pairs.join("; ")}.${note}`;
    }
  }
  // divergence / compare / disagree
  if (/(diverg|disagree|compare|smith|genetically)/.test(q)) {
    const d = bundle.divergence;
    if (d) {
      const movers = (d.notable_movers ?? []).slice(0, 5).map((m) => m?.germplasm_id).filter(Boolean).join(", ");
      return `The transparent and genetically-aware indices have a rank correlation of ${d.rank_correlation ?? "—"}. Notable movers: ${movers || "none reported"}.${note}`;
    }
  }
  // top / best / rank / advance
  if (/(top|best|rank|advance|select|winner)/.test(q)) {
    const label = seg ?? segs[0];
    return `Top candidates for "${label}" (transparent weighted index): ${topForSegment(bundle, label)}.${note}`;
  }

  // overview fallback
  const traitIds = bundle.traits?.map((t) => t.variable_id) ?? [];
  const nGeno = bundle.traits?.[0]?.effects?.length ?? 0;
  return `This analysis covers ${nGeno} genotypes across ${traitIds.length} traits (${traitIds.join(", ")}), with ${segs.length} target market(s): ${segs.join(", ") || "—"}. Top for ${segs[0] ?? "the default market"}: ${topForSegment(bundle, segs[0])}. Ask about a trait's heritability, a genetic correlation, the transparent-vs-genetic divergence, or the top candidates for a target market.${note}`;
}
