// Grounded Q&A over the result bundle (ADR-0002) — the product's trust promise made real. A live
// answer is GENERATED by Claude under a grounding prompt, then VERIFIED by the runtime guardrail: every
// figure and every germplasm/trait/market name it states must exist in the bundle (checkGrounding). If
// not, we regenerate once; if it still doesn't verify, we never show the unverified answer — we surface
// a verified summary plus a reliability warning. So "no fabricated numbers" is enforced, not hoped.
// With no API key, a deterministic offline answerer (grounded by construction) covers the common asks.
import type { ResultBundle } from "@verdant/contracts";
import { bundleDigest, segmentsOf } from "./digest";
import { complete } from "./llm";
import { checkGrounding } from "./grounding";

const GROUNDED_SYSTEM = `You are Verdant's breeding-analysis assistant — a grounded analyst that helps a
working plant breeder act on a completed trial analysis.

Speak to a breeder in plain, confident language. Use their vocabulary (BLUP, GCA, heritability, genetic
correlation, target market) without over-explaining. Lead with the answer, then the why. Keep it tight.

GROUNDING — non-negotiable; this is the product's core promise:
- The RESULT BUNDLE DIGEST below is your ONLY source of facts. Treat it as the breeder's real data.
- Every NUMBER you state must appear verbatim in the digest. Do NOT compute, derive, average, sum,
  convert to a percentage, or estimate any figure. If a number you'd want is not in the digest, do not
  state one — say it isn't available and, if useful, what analysis would produce it.
- Only name germplasm, traits, and target markets that appear in the digest. Never invent a line,
  trait, or market name, and never alter one.
- Never fill a gap with a plausible-sounding number or name. A missing answer is fine; a fabricated one
  is not.
- Be decision-useful: cite the specific figures you rely on, and flag the caveats a breeder should know
  (e.g. a low-heritability trait gives a less reliable ranking).`;

export interface Answer {
  text: string;
  /** 'live' = generated by the model; 'offline' = the deterministic key-free answerer. */
  mode: "live" | "offline";
  model: string | null;
  /** Every figure + name in `text` was checked against the bundle and verified. */
  verified: boolean;
  /** The live model produced an answer we could NOT verify (even after one retry); `text` is a
   *  verified fallback summary and the UI should warn the breeder. */
  flagged: boolean;
  /** The tokens that failed verification on a flag — for transparency / logging. */
  unverified?: string[];
}

/**
 * Grounded answer with the runtime guardrail. Live answers are verified before they reach the breeder;
 * a fabricated figure or name triggers one regenerate, then a warned, verified fallback.
 */
export async function answer(question: string, bundle: ResultBundle): Promise<Answer> {
  const system = `${GROUNDED_SYSTEM}\n\n=== RESULT BUNDLE DIGEST ===\n${bundleDigest(bundle)}`;

  const first = await complete(system, question);
  if (!first) {
    // No credential → the deterministic offline answerer (grounded by construction).
    return { text: answerOffline(question, bundle), mode: "offline", model: null, verified: true, flagged: false };
  }
  const model = first.model;
  const offline = (): Answer => ({ text: answerOffline(question, bundle), mode: "offline", model, verified: true, flagged: false });

  const firstText = first.text.trim();

  // Empty model output (e.g. the token budget was spent on thinking) — retry once for a concise answer;
  // if still empty, fall back to a grounded summary. An empty answer must never render as "verified".
  if (!firstText) {
    const retry = (await complete(system, `${question}\n\nAnswer concisely in plain text. If the results don't contain what's needed, say so briefly.`))?.text.trim() ?? "";
    if (!retry) return offline();
    const gr = checkGrounding(retry, bundle);
    if (gr.grounded) return { text: retry, mode: "live", model, verified: true, flagged: false };
    return { text: answerOffline(question, bundle), mode: "offline", model, verified: false, flagged: true, unverified: [...gr.unverifiedNumbers, ...gr.unverifiedEntities] };
  }

  let g = checkGrounding(firstText, bundle);
  if (g.grounded) return { text: firstText, mode: "live", model, verified: true, flagged: false };

  // Regenerate ONCE, telling the model exactly what failed.
  const offenders = [...g.unverifiedNumbers, ...g.unverifiedEntities];
  const correction = `${question}\n\n[Verification failed] Your previous answer referenced values or names not present in the results: ${offenders.join(", ")}. Answer again using ONLY figures and germplasm/trait/market names that appear verbatim in the results above. Do not compute or estimate; if a figure isn't present, say it isn't available.`;
  const second = (await complete(system, correction))?.text.trim() ?? "";
  if (second) {
    g = checkGrounding(second, bundle);
    if (g.grounded) return { text: second, mode: "live", model, verified: true, flagged: false };
  }

  // Still unverifiable → never show it. Surface a verified summary and flag it for the breeder.
  return {
    text: answerOffline(question, bundle),
    mode: "offline",
    model,
    verified: false,
    flagged: true,
    unverified: [...new Set(offenders)],
  };
}

/** The eval/CI entrypoint — plain string, deterministic, no credential needed. Conforms to the
 *  evals/groundedness VERDANT_ANSWERER contract: answer(question, bundle) -> string. */
export async function answerText(question: string, bundle: ResultBundle): Promise<string> {
  return (await answer(question, bundle)).text;
}

// --- Offline deterministic answerer ------------------------------------------------------------
// Handles a few common intents straight from the bundle (all numbers are bundle figures, so it passes
// the groundedness checker). Not natural language — a stand-in until an API key enables the live path.

function topForSegment(bundle: ResultBundle, seg: string | undefined, n = 5): string {
  const idx = bundle.indices?.find((i) => i.kind === "weighted" && (!seg || i.segment_id === seg))
    ?? bundle.indices?.find((i) => i.kind === "weighted");
  const rows = (idx?.ranking ?? []).slice(0, n).map((r) => `#${r.rank} ${r.germplasm_id} (index ${r.score ?? "—"})`);
  return rows.length ? rows.join(", ") : "no ranking available";
}

/** The deterministic, key-free answerer (also the CI groundedness gate's subject). Every number it
 *  emits comes from the bundle, so its output is grounded by construction. */
export function answerOffline(question: string, bundle: ResultBundle): string {
  const q = question.toLowerCase();
  const segs = segmentsOf(bundle);
  const seg = segs.find((s) => q.includes(s.toLowerCase()));
  const note = ""; // messaging (offline / verified / flagged) is the UI's job, not the answer body's.

  // heritability / h2
  if (/(heritab|h2|h²)/.test(q)) {
    const t = bundle.traits?.find((tr) => q.includes(tr.variable_id.toLowerCase()));
    if (t) return `Heritability (h²) of ${t.variable_id} is ${t.heritability?.value ?? "—"}.${note}`;
    const all = (bundle.traits ?? []).map((tr) => `${tr.variable_id} h²=${tr.heritability?.value ?? "—"}`).join("; ");
    return `Per-trait heritability: ${all}.${note}`;
  }
  // correlation
  if (/correlat/.test(q)) {
    const gc = bundle.genetic_correlations;
    if (gc?.variable_ids?.length && gc.matrix?.length) {
      const pairs: string[] = [];
      for (let i = 0; i < gc.variable_ids.length; i++)
        for (let j = i + 1; j < gc.variable_ids.length; j++)
          pairs.push(`${gc.variable_ids[i]} × ${gc.variable_ids[j]} = ${gc.matrix[i]?.[j] ?? "—"}`);
      return `Genetic correlations: ${pairs.join("; ")}.${note}`;
    }
  }
  // divergence / compare / disagree
  if (/(diverg|disagree|compare|smith|genetically)/.test(q)) {
    const d = bundle.divergence;
    if (d) {
      const movers = (d.notable_movers ?? []).slice(0, 5).map((m) => m?.germplasm_id).filter(Boolean).join(", ");
      return `The transparent and genetically-aware indices have a rank correlation of ${d.rank_correlation ?? "—"}. Notable movers: ${movers || "none reported"}.${note}`;
    }
  }
  // top / best / rank / advance
  if (/(top|best|rank|advance|select|winner)/.test(q)) {
    const label = seg ?? segs[0];
    return `Top candidates for "${label}" (transparent weighted index): ${topForSegment(bundle, label)}.${note}`;
  }

  // overview fallback
  const traitIds = bundle.traits?.map((t) => t.variable_id) ?? [];
  const nGeno = bundle.traits?.[0]?.effects?.length ?? 0;
  return `This analysis covers ${nGeno} genotypes across ${traitIds.length} traits (${traitIds.join(", ")}), with ${segs.length} target market(s): ${segs.join(", ") || "—"}. Top for ${segs[0] ?? "the default market"}: ${topForSegment(bundle, segs[0])}. Ask about a trait's heritability, a genetic correlation, the transparent-vs-genetic divergence, or the top candidates for a target market.${note}`;
}
